//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Middleware.CADService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CADService.CAD_Interface")]
    public interface CAD_Interface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CAD_Interface/Authenticate", ReplyAction="http://tempuri.org/CAD_Interface/AuthenticateResponse")]
        bool Authenticate(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CAD_Interface/Authenticate", ReplyAction="http://tempuri.org/CAD_Interface/AuthenticateResponse")]
        System.Threading.Tasks.Task<bool> AuthenticateAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CAD_Interface/CheckExistence", ReplyAction="http://tempuri.org/CAD_Interface/CheckExistenceResponse")]
        bool CheckExistence(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CAD_Interface/CheckExistence", ReplyAction="http://tempuri.org/CAD_Interface/CheckExistenceResponse")]
        System.Threading.Tasks.Task<bool> CheckExistenceAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CAD_InterfaceChannel : Middleware.CADService.CAD_Interface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CAD_InterfaceClient : System.ServiceModel.ClientBase<Middleware.CADService.CAD_Interface>, Middleware.CADService.CAD_Interface {
        
        public CAD_InterfaceClient() {
        }
        
        public CAD_InterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CAD_InterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CAD_InterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CAD_InterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Authenticate(string username, string password) {
            return base.Channel.Authenticate(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> AuthenticateAsync(string username, string password) {
            return base.Channel.AuthenticateAsync(username, password);
        }
        
        public bool CheckExistence(string username) {
            return base.Channel.CheckExistence(username);
        }
        
        public System.Threading.Tasks.Task<bool> CheckExistenceAsync(string username) {
            return base.Channel.CheckExistenceAsync(username);
        }
    }
}
